name: Jolt
options:
  bundleIdPrefix: com.jolt
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

packages:
  JoltCore:
    path: Packages/JoltCore
  JoltKeychain:
    path: Packages/JoltKeychain
  JoltModels:
    path: Packages/JoltModels
  JoltDesignSystem:
    path: Packages/JoltDesignSystem
  JoltNetworking:
    path: Packages/JoltNetworking
  JoltSync:
    path: Packages/JoltSync
  JoltNotifications:
    path: Packages/JoltNotifications
  JoltSubscriptions:
    path: Packages/JoltSubscriptions
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"

targets:
  Jolt:
    type: application
    platform: iOS
    sources:
      - path: Jolt
        excludes:
          - "Widget/**"
    dependencies:
      - package: JoltCore
      - package: JoltKeychain
      - package: JoltModels
      - package: JoltDesignSystem
      - package: JoltNetworking
      - package: JoltSync
      - package: JoltNotifications
      - package: JoltSubscriptions
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - target: JoltWidget
    settings:
      base:
        INFOPLIST_FILE: Jolt/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jolt.reminders
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: Jolt/Info.plist
      properties:
        CFBundleDisplayName: Jolt
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.874217308291-580dfr043s14an56ts5rpu19pl409frf

  JoltWidget:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources:
      - path: Jolt/Widget
    dependencies:
      - package: JoltCore
      - package: JoltModels
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
    settings:
      base:
        INFOPLIST_FILE: Jolt/Widget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jolt.reminders.widget
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Jolt/Widget/JoltWidget.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    info:
      path: Jolt/Widget/Info.plist
      properties:
        CFBundleDisplayName: Jolt Widget
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

schemes:
  Jolt:
    build:
      targets:
        Jolt: all
        JoltWidget: all
    run:
      config: Debug
      storeKitConfiguration: Jolt/Configuration/JoltProducts.storekit
    test:
      config: Debug
      storeKitConfiguration: Jolt/Configuration/JoltProducts.storekit
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
