name: PowerReminders
options:
  bundleIdPrefix: com.vm.power
  deploymentTarget:
    iOS: "18.6"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "JL84E9GK95"

packages:
  PRCore:
    path: Packages/PRCore
  PRKeychain:
    path: Packages/PRKeychain
  PRModels:
    path: Packages/PRModels
  PRDesignSystem:
    path: Packages/PRDesignSystem
  PRNetworking:
    path: Packages/PRNetworking
  PRSync:
    path: Packages/PRSync
  PRNotifications:
    path: Packages/PRNotifications
  PRSubscriptions:
    path: Packages/PRSubscriptions
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"

targets:
  PowerReminders:
    type: application
    platform: iOS
    sources:
      - path: PowerReminders
        excludes:
          - "Widget/**"
    dependencies:
      - package: PRCore
      - package: PRKeychain
      - package: PRModels
      - package: PRDesignSystem
      - package: PRNetworking
      - package: PRSync
      - package: PRNotifications
      - package: PRSubscriptions
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - target: PowerRemindersWidget
    settings:
      base:
        INFOPLIST_FILE: PowerReminders/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vm.power.reminders
        DEVELOPMENT_TEAM: JL84E9GK95
        IPHONEOS_DEPLOYMENT_TARGET: "18.6"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: PowerReminders/Info.plist
      properties:
        GIDClientID: 874217308291-580dfr043s14an56ts5rpu19pl409frf.apps.googleusercontent.com
        CFBundleDisplayName: Power Reminders
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.874217308291-580dfr043s14an56ts5rpu19pl409frf

  PowerRemindersWidget:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources:
      - path: PowerReminders/Widget
    dependencies:
      - package: PRCore
      - package: PRModels
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
    settings:
      base:
        INFOPLIST_FILE: PowerReminders/Widget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vm.power.reminders.widget
        DEVELOPMENT_TEAM: JL84E9GK95
        IPHONEOS_DEPLOYMENT_TARGET: "18.6"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: PowerReminders/Widget/PowerRemindersWidget.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    info:
      path: PowerReminders/Widget/Info.plist
      properties:
        CFBundleDisplayName: Power Reminders Widget
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

schemes:
  PowerReminders:
    build:
      targets:
        PowerReminders: all
        PowerRemindersWidget: all
    run:
      config: Debug
      storeKitConfiguration: PowerReminders/Configuration/PRProducts.storekit
    test:
      config: Debug
      storeKitConfiguration: PowerReminders/Configuration/PRProducts.storekit
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
